apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mar20-testnewgitops-objdetection
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar20-testnewgitops-objdetection
  name: mar20-testnewgitops-objdetection
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: mar20-testnewgitops-objdetection
